### ISSUE TITLE
Redirecting remote stream to sink

### ISSUE THREAD

**Issue by JulianGerhard21** [DarkMannn/node-radio-mini#12]
Hi DarkMann ! 

First of all - thanks for this awesome repo - good work!

I have a slightly different scenario than yours and I'd like to kindly ask your help / some hints for it. I have
a NodeJS Server which (among other endpoints) accepts incoming websocket messages with the following
information:

```
{
    "event":"websocket:connected",
    "content-type":"audio/l16;rate=16000",
    "language": "en-GB",
    "caller-id": "xxx"
}

Messages that are binary represent the audio of the call. The audio codec presently supported on the WebSocket interface is Linear PCM 16-bit, with either a 8kHz or a 16kHz sample rate, and a 20ms frame size.
To choose the sampling rate set the Content-Type property to audio/l16;rate=16000 or audio/l16;rate=8000 depending on if you need the data at 16kHz or 8kHz. Most real-time transcription services work best with audio at 8kHz.
Each message will be a 20ms sample of the audio from the call. If you choose the 8kHz rate each message will be 320 bytes. Choosing the 16kHz rate will result in each message being 640 bytes.
```` 

Now what I want to actually achieve is, that behind your `/stream` endpoint actually the above mentioned stream gets written into the sink... is that possible?

Kind regards
Julian

**Comment by DarkMannn** [comment]
Hello @JulianGerhard21 ! Thank you for the kind words, I'm glad you like it!

I'm afraid I cannot answer you question properly, it's hard for me to understand it based what you wrote.

Maybe an answer for the websockets that you can find useful - since a websocket message is a chunk of data, you can easily push it into a node stream interface. You just have to implement the custom stream for that.
